### ISSUE TITLE
Missing file: lazyload.jl

### ISSUE THREAD

**Issue by dcjones** [shashi/Canvas.jl#2]
Eager to play around with this, but I think I'm missing a file. Did you forget to commit it, or forget to not include it?

**Comment by shashi** [comment]
Forgot to include it :P Thanks! :)

**Comment by shashi** [comment]
You are also going to need Reactive.jl to be on the flatten branch from github. Also good to keep Patchwork checked out on master.

I don't think anyone else has installed this package before, so I have no idea what other issues exist.

**Comment by shashi** [comment]
You also need Morsel with this PR https://github.com/JuliaWeb/Morsel.jl/pull/34

and you need to run `bower install` inside assets if you want to hack on the HTML/JS/CSS part. You need `vulcanize` npm package to run make in there.
