### ISSUE TITLE
latex.html missing?

### ISSUE THREAD

**Issue by aviks** [shashi/Canvas.jl#9]
trying the `latex.jl` in examples, the following error is displayed in the console: 

```
Asset file /Users/aviks/.julia/v0.3/Canvas/assets/latex.html doesn't exist
 in push! at /Users/aviks/.julia/v0.3/Reactive/src/Reactive.jl:308
 in main at /Users/aviks/.julia/v0.3/Canvas/examples/latex.jl:7
```

**Comment by shashi** [comment]
I think in cases like this getting a separate file is ans overkill. Lot of room for improvement in asset serving

**Comment by shashi** [comment]
turns out the latex example was broken because of an API change to checkbox. Fixed.

**Comment by aviks** [comment]
Thanks, works for me!
